### ISSUE TITLE
BeautifulSoup 3.2.1

### ISSUE THREAD

**Issue by marcelogrsp** [hartleybrody/public-amazon-crawler#17]
```
Collecting BeautifulSoup==3.2.1
  Downloading BeautifulSoup-3.2.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1xhij7ia/BeautifulSoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1xhij7ia/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1xhij7ia/BeautifulSoup/pip-egg-info                
         cwd: /tmp/pip-install-1xhij7ia/BeautifulSoup/                                                             
    Complete output (6 lines):                                                                                     
    Traceback (most recent call last):                                                                             
      File "<string>", line 1, in <module>                                                                         
      File "/tmp/pip-install-1xhij7ia/BeautifulSoup/setup.py", line 22                                             
        print "Unit tests have failed!"                                                                            
              ^                                                                                                    
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?            
    ----------------------------------------                                                                       
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hartleybrody** [comment]
I'll need to see the full stack trace including the command you ran to generate this to know what's really going on. However from the snippet you posted here, this looks like an error with the version of `BeautifulSoup` that you downloaded, which is a third-party library I don't control or maintain.
